### ISSUE TITLE
这个实在太厉害了！ 可不可以文档再丰富点啊

### ISSUE THREAD

**Issue by azl397985856** [reliablejs/reliablejs.github.io#1]
![image](https://cloud.githubusercontent.com/assets/12479470/15804322/b785601e-2b36-11e6-96b4-a79afe14a48b.png)
比如介绍下怎么用你的web， 或者至少这里加上一个命令可以启动web的。目前好像是在makefile中的吧

**Comment by xudafeng** [comment]
@azl397985856 http://macacajs.github.io/macaca/master-deployment.html
